# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talktome', '0003_auto_20170227_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='talktome.Room'),
        ),
    ]
