# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talktome', '0005_auto_20170228_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talktome.User'),
        ),
    ]
