# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talktome', '0006_message_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='talktome.Room'),
        ),
    ]
